###############################################
#                  Group 4                    #
###############################################
#             Anlan Zou (a1899146)            #
#     Czennen Trixter C Tamayo (a1904082)     #
#           Yan Lok Chan (a1902578)           #
#          Yu-Ting Huang (a1903622)           #
###############################################
#         WARNING: VULNERABLE VERSION         #
###############################################

server_name: s4
chat_server:
  host: 10.13.101.145
  port: 12345
exchange_server:
  host: 10.13.101.145
  port: 5555
remote_servers:
  - name: s1
    host: 10.13.101.146
    port: 5555
